baseURL = "/"
languageCode = "en-uk"
title = "Maria Cerase"
theme = "hugo-lodi-theme-master"
googleAnalytics = "UA-8562021-6"
publishDir = "docs"

[params]
    theme_color = "#2B826E"
    description = "Maria Cerase's personal website"
    description_photo = "portfolio.jpg"
    favicon = "favicon.png"
    logo = "logo.png"
    email = "maria.cerase@gmail.com"
    twitter = "SuperMaryCherry"
    dribbble = "ciacicode"
    linkedin = "https://www.linkedin.com/in/mariacerase"
    medium = "SuperMaryCherry"
    github = "ciacicode"

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[params.nav]
    enable = true

[params.hero]
    enable = true
    avatar = "avatar.webp"
    subtitle = "Ciao,   I'm Maria"
    hero_right = ["I am a Product Design professional with 10+ years experience working across B2B and B2C products and platforms. Currently, I work as a Product Lead at MiQ focusing on Design System adoption and improving the usability of internal applications. I also like to bake, play tennis, and do some Python scripting."]
    resume = "MariaCeraseResume.pdf"

[params.process]
    enable = true
    title = "Process"
    subtitle = "My approach to Product Design"


[params.experience]
    enable = true
    title = "Experience"
    subtitle = "Top Jobs"

[params.education]
    enable = true
    title = "Education"
    subtitle = "Diplomas and Degrees"

[params.case_studies]
    enable = true
    title = "Case Studies"
    subtitle = "Selected Works"

[params.services]
    enable = true
    title = "Services"
    subtitle = "Partnerships"

[params.footer]
    enable = true