baseURL = "https://www.mariacerase.com/"
languageCode = "en-uk"
theme = "hugo-winston-theme"
description = "Maria Cerase's personal website"
themesDir = "themes"
title = "MARIACERASE.COM"
publishDir = "public"
keywords = "product designer, portfolio, ux design, freelancer, ui design"
paginate = 3
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"
[[module.imports]]
path="github.com/gohugoio/hugo-mod-bootstrap-scss/v5"

[params]
  google_analytics_id = "G-7PE55B06FD"
  twitter_handle = "@zerostaticio"
  showAuthorOnHomepage = false
  showAuthorOnPosts = true
  showPostsOnHomepage = false
  addDot = false
  addFrame = true
  highlightColor = '#3A0CA3'
  baseColor = "#FCFCFC"
  baseOffsetColor = "#3A0CA3"
  headingColor = "#1E1B18"
  textColor = "#1E1B18"
  dotColor = "#FF006E"
  frameColor="#FF006E"

# markdown config settings https://gohugo.io/getting-started/configuration-markup/#goldmark
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false

[menu]
  [[menu.main]]
    identifier = 'home'
    name = 'Home'
    url = '/'
    weight = 1
