baseURL = "https://ciacicode.github.io/"
languageCode = "en-uk"
title = "Maria Cerase"
theme = "hugo-lodi-theme-master"
googleAnalytics = "UA-8562021-6"
publishDir = "docs"

[params]
    theme_color = "#2B826E"
    description = "Maria Cerase's personal website"
    description_photo = "portfolio.jpg"
    favicon = "favicon.png"
    logo = "logo.png"
    email = "maria.cerase@gmail.com"
    twitter = "SuperMaryCherry"
    dribbble = "ciacicode"
    linkedin = "https://www.linkedin.com/in/mariacerase"
    medium = "SuperMaryCherry"
    github = "ciacicode"

[params.nav]
    enable = true

[params.hero]
    enable = true
    avatar = "avatar.png"
    subtitle = "Ciao,   I'm Maria"
    hero_right = ["I am a Product Lead at MiQ, a programmatic advertising company based in London. I lead the development and the adoption of Fiber, our Design System and write about product best practices. I also like to bake, play tennis, and do some Python scripting."]
    resume = "MariaCeraseResume.pdf"

[params.process]
    enable = false
    title = "Process"
    subtitle = "Full Process Design"


[params.experience]
	enable = true
	title = "Experience"
	subtitle = "Top Jobs"

[params.education]
    enable = false
    title = "Education"
    subtitle = "Diplomas and Degrees"

[params.case_studies]
    enable = false
    title = "Case Studies"
    subtitle = "Selected Works"

[params.footer]
    enable = true
