baseURL = "/"
languageCode = "en-uk"
title = "Maria Cerase"
theme = "sleekfolio"
googleAnalytics = "G-7PE55B06FD"
publishDir = "docs"

[params]
    description = "Maria Cerase's personal website"
    keywords = "product designer, portfolio, ux design, freelancer, ui design, product management"
    description_photo = "portfolio.jpg"
    favicon = "favicon.png"
    email = "maria.cerase@gmail.com"
    mainSections = ['works']
    navfocus = "Product Designer currently working @ MiQ"
    statement = "Get in touch to talk about design, typography, business, food!."

[params.style]
    body_font= "Open+Sans"
    header_font = "Martel"
    font_color = "black"
    accent_color = "#2708a0"

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[params.hero]
    enable = true
    avatar = "img/avatar1.webp"
    subtitle = "Ciao,   I'm Maria"
    intro = "I am a product designer based in London. I like to solve complex problems elegantly and efficiently."
    resume = "MariaCeraseResume.pdf"



[[menu.main]]
  name = "About Me"
  url = "/about"

[[menu.main]]
  name = "Works"
  url = "/works"

[[menu.social]]
    name = "GitHub"
    url = "https://github.com/ciacicode"
    pre = "icofont-github"

[[menu.social]]
    name = "Dribble"
    url = "https://dribbble.com/ciacicode"
    pre = "icofont-dribble"

[[menu.social]]
    name = "Twitter"
    url = "https://twitter.com/SuperMaryCherry"
    pre = "icofont-twitter"

[[menu.social]]
    name = "Medium"
    url = "https://supermarycherry.medium.com"
    pre = "icofont-justify-left"



[[menu.footer]]
  name = "About"
  url = "/about"
