baseURL = "localhost:1313"
languageCode = "en-uk"
title = "Maria Cerase"
theme = "hugo-lodi-theme-master"
googleAnalytics = "#######"

[params]
    theme_color = "#2B826E"
    description = "Maria Cerase's personal website"
    description_photo = "portfolio.jpg"
    favicon = "favicon.png"
    logo = "logo.png"
    email = "maria.cerase@gmail.com"
    twitter = "SuperMaryCherry"
    dribbble = "mariacerase"
    linkedin = "https://www.linkedin.com/in/mariacerase"
    medium = "SuperMaryCherry"
    github = "github"

[params.nav]
    enable = true

[params.hero]
    enable = true
    avatar = "avatar.jpg"
    subtitle = "Ciao,   I'm Maria"
    hero_right = ["Currently working as a Product Lead at MiQ, London, a programmatic advertising company based in London. I look after all our data ingestion APIs that live in an ecosystem with other Big Data processes. I enjoy working in a design driven development process and also apply usability principles to UI and back-end systems both. Incidentally, I am also a keen baker and cook, train and play in a South London Women 11-a-side football team, and enjoy doing a bit of Python scripting."]
    resume = "MariaCeraseResume.pdf"

[params.process]
    enable = false
    title = "Process"
    subtitle = "Full Process Design"


[params.experience]
	enable = true
	title = "Experience"
	subtitle = "Top Jobs"

[params.education]
    enable = false
    title = "Education"
    subtitle = "Diplomas and Degrees"

[params.case_studies]
    enable = false
    title = "Case Studies"
    subtitle = "Selected Works"

[params.footer]
    enable = true
