
name = "Sleekfolio"
license = "MIT"
licenselink = "https://github.com/ciacicode/sleekfolio/blob/master/LICENSE"
description = "Sleekfolio is a bootstrap portfolio template designed by BootstrapMade.com and made into a Hugo Template by ciacicode"
homepage = "https://bootstrapmade.com/"
tags = ['landing-page', 'fast', 'light', 'white', 'modern', 'bootstrapmade', 'hugo-theme', 'hugo-templates', 'bootstrap', 'portfolio', 'responsive', 'clean', 'simple', 'creative', 'contact-form', 'custom-themes', 'mobile', 'minimalistic', 'pages', 'google analytics', 'customizable', 'flexbox', 'presentation', 'product', 'theme', 'typography', 'multilingual', 'gethugothemes']
features = ['bootstrap','responsive']
min_version = "0.64.0"

[author]
name = "ciacicode"
homepage = "https://www.mariacerase.com/"